$(".theTarget").skippr({
  transition:'slide',
  speed:1000,
  easing:'easeInOutQuart',
  navType:'block',
  childrenElementType:'div',
  arrows:true,
  autoPlay:true,
  autoPlayDuration:5000,
  KeyboardOnAlways:true,
  hidePrevious:false
});